server:
  port: 10002

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://192.168.0.108:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.0.108:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    com.blank.gulimall.product.dao: debug
