spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: "jdbc:mysql://192.168.0.108:3306/ecommerce?autoReconnect=true&useUnicode=true&characterSet=utf8"
    username: "root"
    password: "password"
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: EcommercePoolHikari
  redis:
    timeout: 20000
    host: r-wz9xgy8dkpfncoygbwpd.redis.rds.aliyuncs.com
    password: 520992wyz$
    database: 17
    port: 6379
    connect-timeout: 20000