### get service instances
GET http://localhost:9000/ecommerce/ecommerce-nacos-client/nacos-client/service-instance?serviceId=ecommerce-nacos-client
token: imooc
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwiYmxhbmtcIn0iLCJqdGkiOiJkNGZkNzg4Yy00N2QyLTQ5YzQtODgyYS1kZmI1MzYxNmU4MDUiLCJleHAiOjE2NTE1MDcyMDB9.GUzZZcsp75R61gSEsLauBbHk6hQjzh4t6GuO4NtkJlWoshxW_zqhabudwSOqDFXQzooK_HKEAQiBFezF9gaQEMf16d-XMJmELTIuKqk1u1eMSnJMSNjA6AoB789Yv9hFOIuRJ3DMaMrWb6YK9vOhbO9TJLKEiYOGlng0lp_eRVObHUp0jCI2b8JI3cVfDdCGXvbVBsBY2rQAvnd27PeSyVYiBEoliRzOsirNvXuZxmXHVxrIwrIsuBdYAQ8JSuTLF0jBy5Rx25FmygDaIUUPjNESLM0Nf0ohndRBhFJqctJhea_v1FbqVEEZRtAMnfcNe7VkGq_LHyo9CFMdYX_i9A

### sleuth trace info
GET http://localhost:9000/ecommerce/ecommerce-nacos-client/sleuth/trace-info
token: imooc
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwiYmxhbmtcIn0iLCJqdGkiOiJkNGZkNzg4Yy00N2QyLTQ5YzQtODgyYS1kZmI1MzYxNmU4MDUiLCJleHAiOjE2NTE1MDcyMDB9.GUzZZcsp75R61gSEsLauBbHk6hQjzh4t6GuO4NtkJlWoshxW_zqhabudwSOqDFXQzooK_HKEAQiBFezF9gaQEMf16d-XMJmELTIuKqk1u1eMSnJMSNjA6AoB789Yv9hFOIuRJ3DMaMrWb6YK9vOhbO9TJLKEiYOGlng0lp_eRVObHUp0jCI2b8JI3cVfDdCGXvbVBsBY2rQAvnd27PeSyVYiBEoliRzOsirNvXuZxmXHVxrIwrIsuBdYAQ8JSuTLF0jBy5Rx25FmygDaIUUPjNESLM0Nf0ohndRBhFJqctJhea_v1FbqVEEZRtAMnfcNe7VkGq_LHyo9CFMdYX_i9A