server:
  port: 9000

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://192.168.0.108:3306/gulimall_opms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-order
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.0.108:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
