### 创建订单
POST http://localhost:9000/ecommerce/ecommerce-order-service/order/create-order
Content-Type: application/json
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwiYmxhbmtcIn0iLCJqdGkiOiIzZTM1N2M2ZS1iMzFmLTQ5NWQtOTg3ZS01MzVmY2FjM2ExNTkiLCJleHAiOjE2NTI1NDQwMDB9.Lm2VtJjU4M4yGZygL3el4DNUZaHEj2oYjwVvHY1N5ZuxPKQdVv1jqc_48KOYox9wlVma5RmBz2Ebe5P1JLm225IBuZxOz8DLUkSXnRP45JEccsfmTe1MHP6n9hIGAj6-wtIdvxyYOczxOIplMf6ai9ppR8W711Wr-aPJ3jGmbcy-jtZdIV1UjUPfoyalZqHBaf_-no1PuC2aA8s69pe1U8cnpvq_YPnqizwHrhLI19w-WiAzAZVPcuvnsOGvFBskybz9IlYfvoGXoZOuWV7W5dXvnZGPw4G1qX_PcC0ezw6kH0t65QYqNPRXU_SbSSWo6QGTaG_0F_Wnc0G6nZ4s8Q

{
  "userAddress": 1,
  "orderItems": [
    {
      "goodsId": 1,
      "count": 10
    },
    {
      "goodsId": 2,
      "count": 20
    }
  ]
}

### 查询订单
GET http://localhost:9000/ecommerce/ecommerce-order-service/order/page-simple-order-detail
Content-Type: application/json
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwiYmxhbmtcIn0iLCJqdGkiOiJiODAxMDBiMy02M2ViLTQyMDAtODg4Ni1kOTQ0MDU0M2Y3YWMiLCJleHAiOjE2NTIxOTg0MDB9.AwLhL5JXym6KYiahjkpVxxIRqb9T1XlP27GCQk05iAGMCejKtiuqDcQwQMQb-z78RPYVOUkgL9_9V3KJokNVzw9O8aBl6w5aaDtZ0S0n84BK8uoe-wruFCbSbDcBuIBc2Bh0cgmgofDQAIVCsSzoRH8eIdHbLY5GTq5WWPC3H7oAe4Mrk3gttWL_IHT6f1CoD4c5Coi5Hy1lkaSVz1oVxPEDG2C9KnXAT0l0BoNAzSwWHfvglYRBP_dBRopqq5cyTifcUgITC1NbFqbKIRfO3qL0jrPvXeC3M2GOsVe7R2vT1lZow6J8EQIWwB0g8y7_ufStoJWTwOHeplxs_DoQDw
