### 创建订单
POST http://localhost:9000/ecommerce/ecommerce-order-service/order/create-order
Content-Type: application/json
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwiYmxhbmtcIn0iLCJqdGkiOiI1YmUzYjI4My1hZGNkLTQ5NmItOTEzNy1jNmRjOWVmNzU2ZDYiLCJleHAiOjE2NTIzNzEyMDB9.XSnDIo6lQ9baNBNQ0997k8klPbXhYENsw7pMXF-rvj27QH3g3u_780diZv3U9mqlg-BvYtaisE2GWiBlmN8zOYCvQ8FOuoSNI3ruXCcQWXac_2mOmdcshmkeLekzXlPjrKbX3aE6CfDFETPMg_bVRwArhSzRYxuCHgb-NdeuVjxyJKcP2n4KyNtpeXDcsSDPuMPc8n7ZUX4YZQ2R3Mm71O7YXMy_JP2OMF9jj99_uR5Q3kTF4zzbrPz2zmuP7KHwrGuFKrI0HOuZc8GG4rqyoo1AMOZ6jV7BMN3YaBiRc-NYtalPov_ux2Anv3bCAdG-Rq0rFVCPwdzv5fEaKscUqQ

{
  "userAddress": 1,
  "orderItems": [
    {
      "goodsId": 1,
      "count": 10
    },
    {
      "goodsId": 2,
      "count": 20
    }
  ]
}

### 查询订单
GET http://localhost:9000/ecommerce/ecommerce-order-service/order/page-simple-order-detail
Content-Type: application/json
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwiYmxhbmtcIn0iLCJqdGkiOiJiODAxMDBiMy02M2ViLTQyMDAtODg4Ni1kOTQ0MDU0M2Y3YWMiLCJleHAiOjE2NTIxOTg0MDB9.AwLhL5JXym6KYiahjkpVxxIRqb9T1XlP27GCQk05iAGMCejKtiuqDcQwQMQb-z78RPYVOUkgL9_9V3KJokNVzw9O8aBl6w5aaDtZ0S0n84BK8uoe-wruFCbSbDcBuIBc2Bh0cgmgofDQAIVCsSzoRH8eIdHbLY5GTq5WWPC3H7oAe4Mrk3gttWL_IHT6f1CoD4c5Coi5Hy1lkaSVz1oVxPEDG2C9KnXAT0l0BoNAzSwWHfvglYRBP_dBRopqq5cyTifcUgITC1NbFqbKIRfO3qL0jrPvXeC3M2GOsVe7R2vT1lZow6J8EQIWwB0g8y7_ufStoJWTwOHeplxs_DoQDw
