### 创建订单
POST http://localhost:9000/ecommerce/ecommerce-order-service/order/create-order
Content-Type: application/json
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwiYmxhbmtcIn0iLCJqdGkiOiI3M2VmMzgyOC1kYjg0LTRmZDYtOTIyMC02YjVlNmE5ZWIwZmQiLCJleHAiOjE2NTI0NTc2MDB9.kiQZOvySZ4126Ve-rxS_M4hb2D3Ez1OBfykvu9zQbprX7MejuClYro9-hqIgmmKtbCdvmwiikgV9ema9GqtgeMl29XeNAU_sfUH6XvW3SBTE8ZE0Spqgm5FrNU-5VD96NiKOIIcC5oeFcn751U2iZYN-eUN7sOJYZfoGGRNk6Crz6yRPWH5MCbN20yg_xom6PekfczMwVpSEhvRNHtmF7XtjUot6R-Q6JTGEQm3MMnJSrplT6nSvp0o-xgSRuGeJbXiJ8DhwYU-n0ETsMD8fusLAyUEQiN2PBCFk6jiUbCwm4QCqTqwQgWXGTjd6ijG1j6Gft4tdCfMs8Nu49nPDRg

{
  "userAddress": 1,
  "orderItems": [
    {
      "goodsId": 1,
      "count": 10
    },
    {
      "goodsId": 2,
      "count": 20
    }
  ]
}

### 查询订单
GET http://localhost:9000/ecommerce/ecommerce-order-service/order/page-simple-order-detail
Content-Type: application/json
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwiYmxhbmtcIn0iLCJqdGkiOiJiODAxMDBiMy02M2ViLTQyMDAtODg4Ni1kOTQ0MDU0M2Y3YWMiLCJleHAiOjE2NTIxOTg0MDB9.AwLhL5JXym6KYiahjkpVxxIRqb9T1XlP27GCQk05iAGMCejKtiuqDcQwQMQb-z78RPYVOUkgL9_9V3KJokNVzw9O8aBl6w5aaDtZ0S0n84BK8uoe-wruFCbSbDcBuIBc2Bh0cgmgofDQAIVCsSzoRH8eIdHbLY5GTq5WWPC3H7oAe4Mrk3gttWL_IHT6f1CoD4c5Coi5Hy1lkaSVz1oVxPEDG2C9KnXAT0l0BoNAzSwWHfvglYRBP_dBRopqq5cyTifcUgITC1NbFqbKIRfO3qL0jrPvXeC3M2GOsVe7R2vT1lZow6J8EQIWwB0g8y7_ufStoJWTwOHeplxs_DoQDw
